version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    groups:
      minor-patch-updates:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      major-updates:
        applies-to: version-updates
        update-types:
          - "major"
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: 'chore(deps):'

  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "main"
    versioning-strategy: increase-if-necessary
    schedule:
      interval: "daily"
    groups:
      minor-patch-updates:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      major-updates:
        applies-to: version-updates
        update-types:
          - "major"
        patterns:
          - "*"
    commit-message:
      prefix: 'chore(deps):'
